### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by MarketingPip** [dreamcatcher-tech/enquirer-browserify#2]
@inverted-capital - any chance I could get a demo on how to use this in browser?

**Comment by inverted-capital** [comment]
https://github.com/dreamcatcher-tech/dreamcatcher-stack/blob/master/pkg/dos/src/read.js

It works the same as the equirer module here, from which it was forked: https://www.npmjs.com/package/enquirer

I forked it to ensure it worked in a web browser.

If you do not need a web browser, then you should use the original 😄

**Comment by MarketingPip** [comment]
@inverted-capital - I am facing issues with:

```js
keypress.listen = (options = {}, onKeypress) => {
  let { stdin } = options;

  if (!stdin || (stdin !== process.stdin && !stdin.isTTY && !stdin.isMock)) {
    throw new Error("Invalid stream passed");
  }
```

When I pass it a stdin such as prompt etc...

**Comment by inverted-capital** [comment]
Honestly I totally abandoned this approach - it is really hard to make a terminal library work in the browser - what are you trying to achieve ?

**Comment by inverted-capital** [comment]
You need to use this library for stdin: https://www.npmjs.com/package/mock-stdin-browserify

The whole experience is a bit of a nightmare.  I did get it all working, but I should have quit earlier.

**Comment by MarketingPip** [comment]
@inverted-capital - yeah I am not to sure what I am doing. This is my third try now - and weirdly enough I tried that library already but tried again for fun lol.

```js
import stdInputHandler from "https://esm.sh/mock-stdin"

import Enquirer from "https://esm.sh/enquirer-browserify"

 // { username: 'jonschlinkert' }
const stdin = stdInputHandler.stdin()


const stdout = {write:function(...val){
  console.log(val)
}}


const enquirer = new Enquirer({stdin:stdin, stdout})

const response =   await enquirer.prompt({
  type: 'input',
  name: 'username',
  message: 'What is your username?'
});

let btn = document.getElementById("btn");
btn.addEventListener("click", (event) => {
stdin.send("Some text", "ascii");
});



 
console.log(response);
```

**Comment by inverted-capital** [comment]
I had to patch the stdin lib. You need this one https://www.npmjs.com/package/mock-stdin-browserify

I'll try dig up a working example for you tomorrow if you like pain

**Comment by MarketingPip** [comment]
@inverted-capital - tbh I would love that / appreciate that big time. ps; if you have any resources in terms of parsing / handling escape sequences (assuming you do from your knowledge by this package. I would also be grateful).

**Comment by MarketingPip** [comment]
@inverted-capital  - hey! Any chance I can still grab that example! lol
